version: "3.3"
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@dqevectr9gse4kr1_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=Admin
      - spring.datasource.password=OracleCloud123
    restart: always
